# Generated by Django 4.2.7 on 2023-12-03 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlledBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Forklift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.CharField(max_length=32)),
                ('engine_serial_number', models.CharField(max_length=32)),
                ('transmission_serial_number', models.CharField(max_length=32)),
                ('drive_axle_serial_number', models.CharField(max_length=32)),
                ('controlled_bridge_serial_number', models.CharField(max_length=32)),
                ('delivery_contract', models.CharField(max_length=32)),
                ('date_of_shipment', models.DateField()),
                ('end_user', models.CharField(max_length=64)),
                ('delivery_address', models.CharField(max_length=256)),
                ('equipment', models.CharField(max_length=256)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.client')),
                ('controlled_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.controlledbridgemodel')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.driveaxlemodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.enginemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NatureRefusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='To',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating', models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')),
                ('orders_number', models.CharField(max_length=32, verbose_name='№ заказ-наряда')),
                ('orders_date', models.DateField(verbose_name='дата заказ-наряда')),
                ('organization', models.CharField(max_length=32, verbose_name='Организация, проводившая ТО')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.forklift', verbose_name='Зав. № машины')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.service_company', verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.typeto', verbose_name='Вид Тo')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='forklift',
            name='model_equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.modelequipment'),
        ),
        migrations.AddField(
            model_name='forklift',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.service_company'),
        ),
        migrations.AddField(
            model_name='forklift',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.transmissionmodel'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_date', models.DateField(verbose_name='Дата отказа')),
                ('operating', models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час')),
                ('order_description', models.TextField(verbose_name='Описание отказа')),
                ('used_spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.IntegerField(default=0, verbose_name='Время простоя техники')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.forklift', verbose_name='Зав. № машины')),
                ('order_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.naturerefusal', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lift_truck.service_company', verbose_name='Сервисная компания')),
            ],
            options={
                'ordering': ['-orders_date'],
            },
        ),
    ]
